/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyTicketsRouteImport } from './routes/my-tickets'
import { Route as MyAccountRouteImport } from './routes/my-account'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as CreateTicketRouteImport } from './routes/create-ticket'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketIdRouteImport } from './routes/ticket.$id'
import { Route as MyTicketIdRouteImport } from './routes/my-ticket.$id'
import { Route as EditTicketIdRouteImport } from './routes/edit-ticket.$id'
import { Route as CreateTicketTmIdRouteImport } from './routes/create-ticket.$tmId'

const MyTicketsRoute = MyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAccountRoute = MyAccountRouteImport.update({
  id: '/my-account',
  path: '/my-account',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTicketRoute = CreateTicketRouteImport.update({
  id: '/create-ticket',
  path: '/create-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketIdRoute = TicketIdRouteImport.update({
  id: '/ticket/$id',
  path: '/ticket/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTicketIdRoute = MyTicketIdRouteImport.update({
  id: '/my-ticket/$id',
  path: '/my-ticket/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EditTicketIdRoute = EditTicketIdRouteImport.update({
  id: '/edit-ticket/$id',
  path: '/edit-ticket/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTicketTmIdRoute = CreateTicketTmIdRouteImport.update({
  id: '/$tmId',
  path: '/$tmId',
  getParentRoute: () => CreateTicketRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/create-ticket': typeof CreateTicketRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/favorites': typeof FavoritesRoute
  '/my-account': typeof MyAccountRoute
  '/my-tickets': typeof MyTicketsRoute
  '/create-ticket/$tmId': typeof CreateTicketTmIdRoute
  '/edit-ticket/$id': typeof EditTicketIdRoute
  '/my-ticket/$id': typeof MyTicketIdRoute
  '/ticket/$id': typeof TicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/create-ticket': typeof CreateTicketRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/favorites': typeof FavoritesRoute
  '/my-account': typeof MyAccountRoute
  '/my-tickets': typeof MyTicketsRoute
  '/create-ticket/$tmId': typeof CreateTicketTmIdRoute
  '/edit-ticket/$id': typeof EditTicketIdRoute
  '/my-ticket/$id': typeof MyTicketIdRoute
  '/ticket/$id': typeof TicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/create-ticket': typeof CreateTicketRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/favorites': typeof FavoritesRoute
  '/my-account': typeof MyAccountRoute
  '/my-tickets': typeof MyTicketsRoute
  '/create-ticket/$tmId': typeof CreateTicketTmIdRoute
  '/edit-ticket/$id': typeof EditTicketIdRoute
  '/my-ticket/$id': typeof MyTicketIdRoute
  '/ticket/$id': typeof TicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/create-ticket'
    | '/discover'
    | '/favorites'
    | '/my-account'
    | '/my-tickets'
    | '/create-ticket/$tmId'
    | '/edit-ticket/$id'
    | '/my-ticket/$id'
    | '/ticket/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/create-ticket'
    | '/discover'
    | '/favorites'
    | '/my-account'
    | '/my-tickets'
    | '/create-ticket/$tmId'
    | '/edit-ticket/$id'
    | '/my-ticket/$id'
    | '/ticket/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/create-ticket'
    | '/discover'
    | '/favorites'
    | '/my-account'
    | '/my-tickets'
    | '/create-ticket/$tmId'
    | '/edit-ticket/$id'
    | '/my-ticket/$id'
    | '/ticket/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CreateTicketRoute: typeof CreateTicketRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  FavoritesRoute: typeof FavoritesRoute
  MyAccountRoute: typeof MyAccountRoute
  MyTicketsRoute: typeof MyTicketsRoute
  EditTicketIdRoute: typeof EditTicketIdRoute
  MyTicketIdRoute: typeof MyTicketIdRoute
  TicketIdRoute: typeof TicketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-tickets': {
      id: '/my-tickets'
      path: '/my-tickets'
      fullPath: '/my-tickets'
      preLoaderRoute: typeof MyTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-account': {
      id: '/my-account'
      path: '/my-account'
      fullPath: '/my-account'
      preLoaderRoute: typeof MyAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-ticket': {
      id: '/create-ticket'
      path: '/create-ticket'
      fullPath: '/create-ticket'
      preLoaderRoute: typeof CreateTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$id': {
      id: '/ticket/$id'
      path: '/ticket/$id'
      fullPath: '/ticket/$id'
      preLoaderRoute: typeof TicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-ticket/$id': {
      id: '/my-ticket/$id'
      path: '/my-ticket/$id'
      fullPath: '/my-ticket/$id'
      preLoaderRoute: typeof MyTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-ticket/$id': {
      id: '/edit-ticket/$id'
      path: '/edit-ticket/$id'
      fullPath: '/edit-ticket/$id'
      preLoaderRoute: typeof EditTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-ticket/$tmId': {
      id: '/create-ticket/$tmId'
      path: '/$tmId'
      fullPath: '/create-ticket/$tmId'
      preLoaderRoute: typeof CreateTicketTmIdRouteImport
      parentRoute: typeof CreateTicketRoute
    }
  }
}

interface CreateTicketRouteChildren {
  CreateTicketTmIdRoute: typeof CreateTicketTmIdRoute
}

const CreateTicketRouteChildren: CreateTicketRouteChildren = {
  CreateTicketTmIdRoute: CreateTicketTmIdRoute,
}

const CreateTicketRouteWithChildren = CreateTicketRoute._addFileChildren(
  CreateTicketRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CreateTicketRoute: CreateTicketRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  FavoritesRoute: FavoritesRoute,
  MyAccountRoute: MyAccountRoute,
  MyTicketsRoute: MyTicketsRoute,
  EditTicketIdRoute: EditTicketIdRoute,
  MyTicketIdRoute: MyTicketIdRoute,
  TicketIdRoute: TicketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
